### ISSUE TITLE
The usage of calcite in Flink may be a starting point/good example for us

### ISSUE THREAD

**Issue by lmatz** [TatianaJin/husky-sql#1]
How about porting some code into our repo. The use of calcite in Flink can help us avoid some pitfalls in the use of calcite.

**Comment by lmatz** [comment]
I intend to move the "convert sub-queries before query decorrelation" part, "convert table references" part, "decorrelate" part and "normalize the logical plan" part first.

**Comment by TatianaJin** [comment]
Yes. I think Flink provides a very good example. It would be very nice of you to build up the framework first and go through with us including the FYPs. Initially i create this repo just to establish a framework for the FYP and 5120 course project. So we may leave the detailed implementations and ask for their understanding and creativity.
